
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def create_email_html(data):
    """Create a beautiful HTML email from the sentiment data"""
    
    # Extract key stats
    overall_sentiment = data.get("overall_sentiment", 0)
    sentiment_label = data.get("overall_label", "Neutral")
    last_updated = datetime.fromisoformat(data.get("last_updated", datetime.now().isoformat())).strftime("%B %d, %Y")
    
    # Color logic
    color = "#6C757D" # Neutral
    if sentiment_label == "Positive":
        color = "#28A745"
    elif sentiment_label == "Negative":
        color = "#DC3545"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #222; max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }}
            .logo {{ font-size: 24px; font-weight: bold; color: #222; text-decoration: none; }}
            .sentiment-card {{ background-color: #f8f9fa; border-radius: 8px; padding: 25px; text-align: center; margin-bottom: 30px; }}
            .sentiment-score {{ font-size: 48px; font-weight: bold; color: {color}; margin: 10px 0; }}
            .sentiment-label {{ font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: {color}; }}
            .section-title {{ font-size: 18px; font-weight: bold; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 30px; margin-bottom: 15px; }}
            .article-item {{ padding: 15px 0; border-bottom: 1px solid #f5f5f5; }}
            .article-title {{ font-size: 16px; font-weight: 600; color: #000; text-decoration: none; display: block; margin-bottom: 5px; }}
            .article-meta {{ font-size: 12px; color: #888; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #888; text-align: center; }}
            .button {{ display: inline-block; padding: 10px 20px; background-color: #222; color: #fff; text-decoration: none; border-radius: 4px; font-size: 14px; margin-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">🤖 AI Sentiment Pulse</div>
            <div style="color: #666; font-size: 14px; margin-top: 5px;">Daily Report &bull; {last_updated}</div>
        </div>

        <div class="sentiment-card">
            <div>Global AI Sentiment</div>
            <div class="sentiment-score">{overall_sentiment:+.3f}</div>
            <div class="sentiment-label">{sentiment_label}</div>
            <div style="font-size: 13px; color: #666; margin-top: 10px;">Analyzed {data.get('total_articles', 0)} articles from top sources</div>
        </div>

        <div class="section-title">Top Stories</div>
    """

    # Add top 5 articles
    for article in data.get("articles", [])[:5]:
        sentiment_icon = "🟢" if article.get("sentiment_label") == "Positive" else "🔴" if article.get("sentiment_label") == "Negative" else "⚪"
        html += f"""
        <div class="article-item">
            <a href="{article.get('link')}" class="article-title">{article.get('headline')}</a>
            <div class="article-meta">
                {sentiment_icon} {article.get('sentiment_label')} &bull; {article.get('source')}
            </div>
        </div>
        """

    html += """
        <div style="text-align: center;">
            <a href="https://iamjohnwatson.github.io/Sentiment-Analysis/" class="button">View Full Dashboard</a>
        </div>

        <div class="footer">
            <p>This report was automatically generated by AI Sentiment Pulse.</p>
            <p>To unsubscribe, please reply to this email.</p>
        </div>
    </body>
    </html>
    """
    return html

def send_newsletter(data):
    """Send the newsletter via SMTP"""
    sender_email = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASSWORD")
    recipients_str = os.environ.get("RECIPIENTS", "")
    smtp_server = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", 587))

    if not sender_email or not password or not recipients_str:
        print("Skipping newsletter: Missing SMTP_USER, SMTP_PASSWORD, or RECIPIENTS.")
        return

    recipients = [r.strip() for r in recipients_str.split(",") if r.strip()]
    if not recipients:
        print("Skipping newsletter: No recipients found.")
        return

    print(f"Preparing newsletter for {len(recipients)} recipients...")

    msg = MIMEMultipart()
    msg['From'] = f"AI Sentiment Pulse <{sender_email}>"
    msg['Subject'] = f"🤖 AI Sentiment Report: {data.get('overall_label')} ({data.get('overall_sentiment'):+.2f})"
    
    # Attach HTML body
    html_content = create_email_html(data)
    msg.attach(MIMEText(html_content, 'html'))

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, password)
        
        # Send to all recipients (bcc style to avoid exposing list if preferred, 
        # but individual sends are better for deliverability often. 
        # For simplicity/speed in this small batch, we iterate.)
        for recipient in recipients:
            del msg['To']
            msg['To'] = recipient
            server.send_message(msg)
            
        server.quit()
        print("✅ Newsletter sent successfully!")
        
    except Exception as e:
        print(f"❌ Error sending newsletter: {e}")

if __name__ == "__main__":
    # Test with dummy data if run directly
    dummy_data = {
        "overall_sentiment": 0.45,
        "overall_label": "Positive",
        "total_articles": 12,
        "last_updated": datetime.now().isoformat(),
        "articles": [
            {"headline": "Test Article 1", "source": "Reuters", "link": "#", "sentiment_label": "Positive"},
            {"headline": "Test Article 2", "source": "BBC", "link": "#", "sentiment_label": "Neutral"},
        ]
    }
    # print(create_email_html(dummy_data))
